<?php
// +----------------------------------------------------------------------
// | ThinkPHP [ WE CAN DO IT JUST THINK IT ]
// +----------------------------------------------------------------------
// | Copyright (c) 2006-2014 http://thinkphp.cn All rights reserved.
// +----------------------------------------------------------------------
// | Licensed ( http://www.apache.org/licenses/LICENSE-2.0 )
// +----------------------------------------------------------------------
// | Author: liu21st <liu21st@gmail.com>
// +----------------------------------------------------------------------

/**
 * ThinkPHP English language package
 */
return array(
    /* core language pachage */ 
    '_MODULE_NOT_EXIST_'     => "Module can't be loaded",
    '_CONTROLLER_NOT_EXIST_' =>	"Controler can't be loaded",
    '_ERROR_ACTION_'         => 'Illegal Action',
    '_LANGUAGE_NOT_LOAD_'    => "Can't load language package",
    '_TEMPLATE_NOT_EXIST_'   => "Template does't exist",
    '_MODULE_'               => 'Module',
    '_ACTION_'               => 'Action',
    '_MODEL_NOT_EXIST_'      => "Model can't be loaded",
    '_VALID_ACCESS_'         => 'No access',
    '_XML_TAG_ERROR_'        => 'XML tag syntax errors',
    '_DATA_TYPE_INVALID_'    => 'Illegal data objects!',
    '_OPERATION_WRONG_'      => 'Operation error occurs',
    '_NOT_LOAD_DB_'          => 'Unable to load the database',
    '_NO_DB_DRIVER_'         => 'Unable to load database driver',
    '_NOT_SUPPORT_DB_'       => 'The system is temporarily not support database',
    '_NO_DB_CONFIG_'         => 'Not define the database configuration',
    '_NOT_SUPPERT_'          => 'The system does not support',
    '_CACHE_TYPE_INVALID_'   => 'Unable to load the cache type',
    '_FILE_NOT_WRITEABLE_'   => 'Directory (file) is not writable',
    '_METHOD_NOT_EXIST_'     => 'The method you requested  does not exist!',
    '_CLASS_NOT_EXIST_'      => 'Instantiating a class does not exist！',
    '_CLASS_CONFLICT_'       => 'Class name conflicts',
    '_TEMPLATE_ERROR_'       => 'Template Engine errors',
    '_CACHE_WRITE_ERROR_'    => 'Cache file write failed!',
    '_TAGLIB_NOT_EXIST_'     => 'Tag library is not defined',
    '_OPERATION_FAIL_'       => 'Operation failed!',
    '_OPERATION_SUCCESS_'    => 'Operation successed!',
    '_SELECT_NOT_EXIST_'     => 'Record does not exist!',
    '_EXPRESS_ERROR_'        => 'Expression errors',
    '_TOKEN_ERROR_'          => "Form's token errors",
    '_RECORD_HAS_UPDATE_'    => 'Record has been updated',
    '_NOT_ALLOW_PHP_'        => 'PHP codes are not allowed in the template',
    '_PARAM_ERROR_'          => 'Parameter error or undefined',
    '_ERROR_QUERY_EXPRESS_'  => 'Query express error',       


    //自定义语言词汇
    'wellcome'=>'Wellcome to',
    'taday-is'=>'Taday is',
    'set-home'=>'Set Home',
    'home'=>'Home',
    'add-like'=>'Add Like',
    
    'language'=>'Language',
    'chinese'=>'中文',
    'english'=>'English',

    'WE-1'=>'Monday',
    'WE-2'=>'Tuesday',
    'WE-3'=>'Wednesday',
    'WE-4'=>'Shursday',
    'WE-5'=>'Friday',
    'WE-6'=>'Saturday',
    'WE-7'=>'Sunday',

    'hit'=>'Hit',
    'ask'=>'Ask',
    'answer'=>'Answer',
    'this-space'=>'Space',
    'jump-tipe'=>'jump tips',
    'page-auto'=>'page will auto',
    'jump'=>'jump',
    'wait-time'=>'Wait',
    'more-details'=>'More Details',
    'last-prodect'=>'Last Prodect',
    'more-prodect'=>'More Prodect',
    'last-news'=>'Last News',
    'more-news'=>'More News',   
    'all-news'=>'All News',  
    'company-photo'=>'Company Photo',
    'prodect-name'=>'Prodect',
    'hot-products'=>'Hot Products',
    'all-products'=>'All Products',
    'current-product'=>'Current Product',
    'product-introduction'=>'Product Introduction',
    'similar-products'=>'Similar Products',
    'result-products'=>'Related Commodities',
    'search'=>'Search',
    'types'=>'type',
    'origin-brand'=>'Origin/Brand',
    'model'=>'Model',
    'texture-material'=>'Material',
    'purchase-quantity'=>'Number',
    'geshu'=>'A',
    'attachment-upload'=>'File',
    'specifications'=>'Speci',
    'use-range'=>'Use Range',
    'immediate-inquiry'=>'Inquiry',
    'send-nquiry'=>'Send Nquiry',
    'send-inquiry'=>'Send Inquiry',
    'inquiry-product'=>'Product',
    'customer-service'=>'Service',
    'second-ways'=>'Second Ways',
    'product-description'=>'Product Description',
    'supplier-information'=>'Supplier Information',
    'business-model'=>'Business Model',
    'the-location'=>'The Location',

    'last-one'=>'Previous One',
    'the-next'=>'Next One',
    'num-result'=>'Num Result',
    'last-page'=>'Last Page',
    'next-page'=>'Next Page',
    'no-more'=>'No Mone',
    'no-data'=>'No Data',



    'username'=>'Username',
    'names'=>'Names',
    'contact-names'=>'Contacter',
    'contact'=>'Contact',
    'phone'=>'Phone',
    'mobile'=>'Mobile',
    'password'=>'Password',
    'code'=>'Code',
    'email'=>'Email',
    'qq'=>'QQ',
    'comlany-name'=>'Comlany Name',
    're-password'=>'Re Password',
    'num'=>'Num',
    'unit'=>'Unit',    
    'bay-tips'=>'Tips',    
    'remark'=>'Remark',   
    'no-value'=>'None',  
    'save-and-send'=>'Save And Send',
    'tips-info'=>'Tips Info',
    'submit'=>'Submit',
    'save'=>'Save',
    'cancel'=>'Cancel',
    'close'=>'Close',
    'reset'=>'Reset',
    
    'resume-delivery'=>'Resume Delivery',
    'recruitment-number'=>'Number',
    'job-responsibilities'=>'Job Responsibilities',
    'job-requirements'=>'Job Requirements',
    'post-treatment'=>'Post Treatment',
    'working-place'=>'Working Place',
    


    //自定义语言短语
    'dy-1'=>'Pless Write The Right Prodect Name!',
    'dy-2'=>'Your need has been submitted to the success and we will handle it as soon as possible!',
    'dy-3'=>'I’m sorry, pless try again later.!',
    'dy-4'=>'Data is being submitted to...',
    'dy-5'=>'Red prompt is required!',
    'dy-6'=>'Such as drawings, process notes',
    'dy-7'=>'Not required, such as specific types, specifications, processing, packaging etc.',
    'dy-8'=>'Leave contact, contact you easily',
    'dy-9'=>'If the customer service contact, please contact me can also, please say at the website of Chen Yi website to see! Thank you',
    'dy-10'=>'Send resume to the above email, we will be the first time as soon as you',
    'dy-11'=>'Hello, there is a question to ask your company...',

    'dy-12'=>'The operation is browser to refuse, if you want to enable this feature, please enter in the address column about: config, and then the item Signed.applets.codebase_principal_support principal support value the true',
    'dy-13'=>'Add Like List fail, Pless Try To Ctrl+D to Do It!',
    'dy-14'=>'Set',
    'dy-15'=>'Be Home Page？',
    'dy-16'=>'Post Ing...',
    'dy-17'=>'Internet Error！, pless try again later!',
    'dy-18'=>'The product is commodity!',

    'dy-19'=>'Don\'t repeat the message!',
    'dy-20'=>'With * field is required!',
    'dy-21'=>'File upload failed!',
    'dy-22'=>'Submit success!',
    'dy-23'=>'To submit the success, has notified the administrator!',
    'dy-24'=>'Submit success, waiting for the administrator to reply!',
    'dy-25'=>'Submission of failure!',
    'dy-26'=>'Don\'t repeat the questions!',
    'dy-27'=>'Data can not be empty!',
);
